name: Nas-tools Build Synology SPK

on:
  push:
    branches: [ master ]
    paths:
      - version.py
      - .github/workflows/build-synology.yml

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Release version
      id: release_version
      run: |
        app_version=$(cat version.py |sed -ne "s/APP_VERSION\s=\s'v\(.*\)'/\1/gp")
        echo "app_version=$app_version" >> $GITHUB_ENV

    - name: Build the synology spk
      run: |
        cp -r synology/ui ./
        sed -i 's/3000/3003/g' config/config.yaml
        sed -i 's/\/config\/logs/\/var\/packages\/nastool\/target\/config\/logs/g' config/config.yaml
        tar -zcvf package.tgz *.py *.txt service/ rmt/ message/ web/ ui/ config/ pt/ utils/
        mkdir spk6
        cp -r package.tgz synology/dsm6/conf synology/dsm6/scripts/ synology/dsm6/INFO synology/CHANGELOG synology/*.PNG synology/*.asc spk6/
        cd spk6/
        chmod 777 scripts/*
        sed -i 's/NASTOOL_VERSION/${{ env.app_version }}/g' INFO
        tar -cvf nastool_dsm_6.x.spk *
        cd ..
        rm -f package.tgz
        tar -zcvf package.tgz *.py *.txt service/ rmt/ message/ web/ ui/ config/ pt/ utils/
        mkdir spk7
        cp -r package.tgz synology/dsm7/conf synology/dsm7/scripts/ synology/dsm7/INFO synology/CHANGELOG synology/*.PNG synology/*.asc spk7/
        cd spk7/
        chmod 777 scripts/*
        sed -i 's/NASTOOL_VERSION/${{ env.app_version }}/g' INFO
        tar -cvf nastool_dsm_7.x.spk *
        cd ..
        mkdir spks
        mv spk6/nastool_dsm_6.x.spk spk7/nastool_dsm_7.x.spk spks/

    - name: Create release
      id: create_release
      uses: actions/create-release@latest
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: v${{ env.app_version }}
        release_name: v${{ env.app_version }}
        body: ${{ github.event.commits[0].message }}
        draft: false
        prerelease: false

    - name: Upload release asset
      id: upload-release-asset
      uses: dwenegar/upload-release-assets@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        release_id: ${{ steps.create_release.outputs.id }}
        assets_path: spks/

    - name: Send telegram message
      uses: appleboy/telegram-action@master
      with:
        to: ${{ secrets.TELEGRAM_TO }}
        token: ${{ secrets.TELEGRAM_TOKEN }}
        message: |
          ${{ github.actor }} created commit:
          Commit message: ${{ github.event.commits[0].message }}
          Repository: ${{ github.repository }}
          See changes: https://github.com/${{ github.repository }}/commit/${{github.sha}}
